name: Package VS Code Extension

on: 
  push:
    tags:
    - '*'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Install vsce
      run: npm install -g vsce

    - name: Package Extension
      run: vsce package

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: extension
        path: "*.vsix"

    - name: Release extension
      uses: ncipollo/release-action@v1
      with:
        artifacts: "*.vsix"
