name: create extension

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Package VS Code extension
      uses: nhedger/package-vscode-extension@v1
      with:
        extensionPath: ./packages/my-extension
