name: create extension

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Package VS Code extension
      uses: nhedger/package-vscode-extension@v1
